Qa canonizer sai
the-canonizer/canonizer_3_Automated_TestCase pull request #2
Opened 2022-05-02 07:42 UTC by saideekshith8

2022-05-03 12:47 UTC, akuks requested changes

2022-05-03 12:47 UTC, akuks commented on CanonizerRegistrationPage.py
> +        sleep(3)
Why is sleep used here?

2022-05-03 12:47 UTC, akuks commented on CanonizerRegistrationPage.py
>          if err == 'Please input your first name!':
Please move 'Please input your first name' in config files

2022-05-04 05:36 UTC, saideekshith8 commented
Hi, Sleep is used because the test runs faster so user cannot see if test
case is executed or not so to see if the steps are executed we use sleep

I'll add First name in Config File

On Tue, May 3, 2022 at 6:17 PM Ashutosh Kukreti ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In CanonizerRegistrationPage.py
> <https://github.com/the-canonizer/canonizer_3_Automated_TestCase/pull/2#discussion_r863736595>
> :
>
> >          self.hover(*RegisterPageIdentifiers.TITLE)
> +        sleep(3)
>
> Why is sleep used here?
> ------------------------------
>
> In CanonizerRegistrationPage.py
> <https://github.com/the-canonizer/canonizer_3_Automated_TestCase/pull/2#discussion_r863737130>
> :
>
> > @@ -108,26 +110,72 @@ def verify_firstname_empty(self, Name):
>
>      def verify_all_fields_empty(self):
>          self.click_register_button()
> -        sleep(2)
> -        self.find_element(*RegisterPageIdentifiers.Register_now).click()
> +        self.find_element(*RegisterPageIdentifiers.REGISTER_NOW).click()
>          self.hover(*RegisterPageIdentifiers.error)
>          err = self.find_element(*RegisterPageIdentifiers.error).text
>          print(err)
>          if err == 'Please input your first name!':
>
> Please move 'Please input your first name' in config files
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/the-canonizer/canonizer_3_Automated_TestCase/pull/2#pullrequestreview-960318508>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYPV6LZQCQJXE3A4R5UWOYLVIEN7DANCNFSM5U3HML4A>
> .
> You are receiving this because you authored the thread.Message ID:
> <the-canonizer/canonizer_3_Automated_TestCase/pull/2/review/960318508@
> github.com>
>

2022-05-06 04:42 UTC, akuks requested changes

2022-05-06 04:42 UTC, akuks commented on Identifiers.py
>  class RegisterPageIdentifiers(object):
Create a New Folder "Name" Identifiers and create new classes there. It'll sort out the code and make it easier to manage

2022-05-06 04:42 UTC, akuks commented on Identifiers.py
> +class AccountSettingPageIdentifier(object):
Same as previous comment

2022-06-02 10:30 UTC, akuks commented
@saideekshith8 Please close this PR.

2022-06-03 05:41 UTC, saideekshith8 commented
The PR is closed, please check ***@***.***

On Thu, Jun 2, 2022 at 4:00 PM Ashutosh Kukreti ***@***.***>
wrote:

> @saideekshith8 <https://github.com/saideekshith8> Please close this PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/the-canonizer/canonizer_3_Automated_TestCase/pull/2#issuecomment-1144704693>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYPV6L7PTDGBBWVI3C4ZSCDVNCEM5ANCNFSM5U3HML4A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-06-08 08:17 UTC, akuks commented
No it is not closed. I can see it open (@saideekshith8 )

2022-06-09 07:18 UTC, closed without merging