Qa canonizer sania
the-canonizer/canonizer_3_Automated_TestCase pull request #5
Opened 2022-07-11 07:22 UTC by saniatg

https://canonizer.atlassian.net/browse/CAN-64
Forgot password automated test scripts

https://canonizer.atlassian.net/browse/CAN-500
Create new topic automates test scripts

2022-07-11 09:55 UTC, akuks requested changes

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +from time import sleep
File name is incorrect. It should be Account where it is `Acoount`

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +        sleep(3)
Please remove sleep

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +        tittle = self.find_element(*AccountSettingPageIdentifier.SOCIAL_OAUTH_VERIFICATION).text
typo in the variable name.

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +        if tittle == 'Social Oauth Verification':
This should come from a common message file.

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +        tittle = self.find_element(*AccountSettingPageIdentifier.CHANGE_PASSWORD).text
Typo in name the variable

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +        if tittle == 'Change Password':
`Change Password` should come from a common message file

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +        tittle = self.find_element(*AccountSettingPageIdentifier.NICK_NAME).text
typo in variable name

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +        if tittle == 'Nick Names':
Do we need to print? I think no

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +        sleep(3)
Please remove sleep from all the places

2022-07-11 09:55 UTC, akuks commented on CanonizerAcoountSettingPage.py
> +        if tittle == 'Incorrect Current Password':
All the messages must come from a common file

2022-07-15 12:27 UTC, saniatg commented
@akuks All changes are done as mentioned by you.

2022-07-18 09:29 UTC, akuks requested changes

2022-07-18 09:29 UTC, akuks commented on CanonizerBrowsePage.py
> +    def Verify_Browse_page_is_opening_when_you_click_on_Browse(self):
function name should start with the smallcase

2022-07-18 09:29 UTC, akuks commented on CanonizerBrowsePage.py
> +    def Verify_all_the_specified_fields_are_present_on_the_Browse_page(self):
function name should start with the smallcase

2022-07-18 09:29 UTC, akuks commented on CanonizerBrowsePage.py
> +        sleep(2)
We are still using sleep?

2022-07-18 09:29 UTC, akuks commented on CanonizerBrowsePage.py
> +    def Check_for_the_validation_of_Select_Namespace_drop_down(self):
function name should start with the smallcase

2022-07-18 09:29 UTC, akuks commented on CanonizerBrowsePage.py
> +        sleep(3)
Are we still using sleep?

2022-07-18 09:43 UTC, saniatg commented on CanonizerBrowsePage.py
> +        sleep(3)
@akuks that was Sai's code. I have deleted that file now.

2022-07-19 07:29 UTC, akuks approved these changes

2022-07-19 07:29 UTC, merged